project/entregas/views.py
"""
.. topic:: entregas (views)

    Planos de Entregas.

"""

# views.py dentro da pasta entregas

from flask import render_template, url_for, flash, redirect, Blueprint, send_from_directory
from flask_login import current_user, login_required
from sqlalchemy import func, case, literal_column, or_, distinct
from sqlalchemy.sql import label
from sqlalchemy.orm import aliased
from project import db, app
from project.models import Unidades, Pessoas, programas, planos_entregas, unidades_integrantes,\
                           avaliacoes, planos_entregas_entregas, planos_trabalhos_entregas, tipos_modalidades, planos_trabalhos_consolidacoes,\
                           planos_trabalhos

from project.entregas.forms import CSV_Form

from datetime import datetime as dt

import os, csv

entregas = Blueprint("entregas",__name__,template_folder='templates')    


## lista planos de entregas

@entregas.route('/lista_pe',methods=['GET','POST'])
@login_required
def lista_pe():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta os planos de entregas.                                                       |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """
        
    unid_dados = db.session.query(Unidades.id, Unidades.sigla, Unidades.path)\
                            .all()

    entregas = db.session.query(planos_entregas_entregas.plano_entrega_id,
                                label('qtd_entregas',func.count(planos_entregas_entregas.id)))\
                         .group_by(planos_entregas_entregas.plano_entrega_id)\
                         .subquery()                                               
                            
    pts_todos_1 = db.session.query(label('pt_id',planos_trabalhos_entregas.plano_trabalho_id.distinct()),
                                   planos_trabalhos_entregas.plano_entrega_entrega_id,
                                   planos_entregas_entregas.plano_entrega_id)\
                            .join(planos_entregas_entregas, planos_entregas_entregas.id == planos_trabalhos_entregas.plano_entrega_entrega_id)\
                            .subquery()
    planos_trab = db.session.query(label('pe_id',pts_todos_1.c.plano_entrega_id.distinct()),
                                   label('qtd_planos_trab',func.count(distinct(pts_todos_1.c.pt_id))))\
                            .group_by(pts_todos_1.c.plano_entrega_id)\
                            .subquery()                      
                                                                                      
                            
    unidades_pai = aliased(Unidades)                                                                          


    hoje = dt.now()
        
    planos_entregas_todos = db.session.query(planos_entregas.id,
                                       planos_entregas.status,
                                       planos_entregas.data_inicio,
                                       planos_entregas.data_fim,
                                       planos_entregas.deleted_at,
                                       entregas.c.qtd_entregas,
                                       planos_trab.c.qtd_planos_trab,
                                       Unidades.sigla,
                                       label('sigla_pai', unidades_pai.sigla),
                                       planos_entregas.unidade_id,
                                       Unidades.unidade_pai_id,
                                       label('vencido',case((planos_entregas.data_fim < hoje, literal_column("'s'")), else_=literal_column("'n'"))),
                                       avaliacoes.nota,
                                       avaliacoes.data_avaliacao,
                                       label('just_avalia',avaliacoes.justificativas),
                                       label('parecer_avalia',avaliacoes.justificativa))\
                                .join(Unidades, Unidades.id == planos_entregas.unidade_id)\
                                .outerjoin(unidades_pai, unidades_pai.id == Unidades.unidade_pai_id)\
                                .outerjoin(entregas, entregas.c.plano_entrega_id == planos_entregas.id)\
                                .outerjoin(planos_trab,planos_trab.c.pe_id == planos_entregas.id)\
                                .outerjoin(avaliacoes,avaliacoes.plano_entrega_id == planos_entregas.id)\
                                .filter(planos_entregas.deleted_at == None)\
                                .order_by(planos_entregas.status, Unidades.sigla, planos_entregas.data_inicio)\
                                .all() 
                               

    quantidade = len(planos_entregas_todos)

    form = CSV_Form()

    if form.validate_on_submit():

        csv_caminho_arquivo = os.path.normpath('/app/project/static/planos_entrega.csv')
        
        dados_a_escrever = [[p.sigla, p.status, p.data_inicio, p.data_fim, p.qtd_entregas, p.qtd_planos_trab, p.nota] for p in planos_entregas_todos]

        header = ['Unidade', 'Status','Início','Fim', 'Qtd. Entregas', 'Qtd. PTs', 'Nota']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', 'planos_entrega.csv')

        return redirect(url_for('static', filename = 'planos_entrega.csv'))        

    return render_template('lista_pe.html', unid_dados = unid_dados,
                                            planos_entregas_todos = planos_entregas_todos,
                                            quantidade = quantidade,
                                            form = form)


## consulta entregas de um plano de entregas

@entregas.route('/<peId>/consulta_entregas')
@login_required
def consulta_entregas(peId):
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta uma lista das entregas de um Plano de Entergas.                              |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """   
    
    plano_entregas = db.session.query(planos_entregas.status,
                                      planos_entregas.data_inicio,
                                      planos_entregas.data_fim, 
                                      Unidades.sigla)\
                               .join(Unidades, Unidades.id == planos_entregas.unidade_id)\
                               .filter(planos_entregas.id == peId).first()
    
    entregas = db.session.query(planos_entregas_entregas).filter(planos_entregas_entregas.plano_entrega_id == peId).all()
    
    
    quantidade = len(entregas)
    
    return render_template("consulta_entregas.html", plano_entregas =plano_entregas, 
                                                     entregas = entregas,
                                                     quantidade = quantidade)
    
    
## lista planos de trabalho vinculados a um plano de entregas

@entregas.route('/<peId>/consulta_pts')
@login_required
def consulta_pts(peId):
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta uma lista de planos de trabalho vinculados a um plano de entregas.           |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """   

    hoje = dt.today().date()
    
    pe = db.session.query(planos_entregas.status,
                          planos_entregas.data_inicio,
                          planos_entregas.data_fim, 
                          Unidades.sigla)\
                   .join(Unidades, Unidades.id == planos_entregas.unidade_id)\
                   .filter(planos_entregas.id == peId).first()
                         

    #subquery que conta avaliações realizadas até em cada pt (exclui as autormáticas futuras)
    avaliacoes_pt = db.session.query(planos_trabalhos_consolidacoes.plano_trabalho_id,
                                     label('qtd_aval',func.count(avaliacoes.id)))\
                              .join(planos_trabalhos_consolidacoes, planos_trabalhos_consolidacoes.id == avaliacoes.plano_trabalho_consolidacao_id)\
                              .group_by(planos_trabalhos_consolidacoes.plano_trabalho_id)\
                              .subquery()                                            
    
    
    planos_trab_pe  = db.session.query(planos_trabalhos.id.distinct(),
                                       planos_trabalhos.data_inicio,
                                       planos_trabalhos.data_fim,
                                       planos_trabalhos.carga_horaria,
                                       planos_trabalhos.forma_contagem_carga_horaria,
                                       planos_trabalhos.status,
                                       planos_trabalhos.tempo_total,
                                       planos_trabalhos.tempo_proporcional,
                                       planos_trabalhos_entregas.plano_trabalho_id,
                                       planos_entregas_entregas.plano_entrega_id,
                                       Pessoas.nome,
                                       Unidades.sigla,
                                       label('forma',tipos_modalidades.nome),
                                       avaliacoes_pt.c.qtd_aval)\

project/entregas/templates/consulta_entregas.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('entregas.lista_pe')}}">Planos de Entregas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Consulta Entregas</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  
  <h4>Entregas do PE</h4>
  <div class="row">
    <div class="col">
      <p>Unidade: <b>{{ plano_entregas.sigla }}</b></p>
    </div>

    <div class="col">
      Vigência: <b>{{plano_entregas.data_inicio.strftime('%d/%m/%Y')}} a {{plano_entregas.data_fim.strftime('%d/%m/%Y')}}</b>
    </div>
    <div class="col">
      Situação: <b>{{ plano_entregas.status }}</b> 
    </div>
  </div>


  {% for e in entregas %}

    <div class="card card border-secondary">
      
      <div class="card-header">
        <div class="row justify-content-between">
          <div class="col-10">
            Entrega: <b>{{e.descricao}}</b>
          </div>
          <div class="col-2 text-right">
            <b>{{entregas.index(e) + 1}}</b>
          </div>
        </div>
        <div class="row">
          <div class="col">
            Descrição: <b>{{e.descricao_entrega}}</b>
          </div>
        </div>
      </div>

      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-4 text-center">
            {% if e.data_fim > plano_entregas.data_fim %} 
              Vigência: <span class="text-danger"><b>{{e.data_inicio.strftime('%d/%m/%Y')}} a {{e.data_fim.strftime('%d/%m/%Y')}}</b></span>
            {% else %}  
              Vigência: <b>{{e.data_inicio.strftime('%d/%m/%Y')}} a {{e.data_fim.strftime('%d/%m/%Y')}}</b>
            {% endif %}  
          </div>
          <div class="col-4 text-center">
            Meta: <b>{{ e.meta|dic_value }} ({{ e.meta|dic_key }})</b> 
          </div>
          <div class="col-4 text-center">
            {% if e.destinatario == None %}
              <b>Destinatário não cadastrado</b>
            {% else %}
              Destinatário: <b>{{e.destinatario}}</b> 
            {% endif %}
          </div>
        </div>
        
        <br>

        {#
        <div class="row justify-content-center">
          <div class="col-5 text-center">  
            {% if e.relatorio %}

                Possui relatório: <a href="#" data-bs-toggle='modal' data-bs-target='#rel_modal{{e.planoEntregasEntregasId}}' class="btn btn-outline-primary btn-sm" role="button">
                  <abbr title="O quanto esta, ou estas, unidades comprometeram de sua capacidade nesta entrega."><i class="fa-solid fa-check"></i></i></abbr>
                </a>
                    
                    <!-- modal visualização de programas de gestão da unidade -->

                    <div class="modal fade" tabindex="-1" role="dialog" id="rel_modal{{e.planoEntregasEntregasId}}">
                      <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h4 class="modal-title">Relatório da entrega <b>{{ e.nome }}</b></h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            {{ e.relatorio }}
                          </div>
                          <div class="modal-footer">
                          </div>
                        </div>
                      </div>
                    </div>

            {% else %}
              Possui relatório: <i class="fa-solid fa-xmark"></i>
            {% endif%}
          </div>  
          <div class="col-5 text-center">
            {% if e.unids_qtd == None %}

              <b>Nenhuma unidade atuando na entrega</b>

            {% else %}

              <a href="#" data-bs-toggle='modal' data-bs-target='#unids_modal{{e.planoEntregasEntregasId}}' class="btn btn-outline-primary btn-sm" role="button">
                <abbr title="O quanto esta, ou estas, unidades comprometeram de sua capacidade nesta entrega."><b>{{e.unids_qtd}}</b></i></abbr>
              </a> Unidade(s) atuando na Entrega
                  
                   <!-- modal visualização de programas de gestão da unidade -->

                  <div class="modal fade" tabindex="-1" role="dialog" id="unids_modal{{e.planoEntregasEntregasId}}">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Unidades atuando na entrega <b>{{ e.nome }}</b></h4>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">

                          <table class="table table-striped table-hover table-sm">
                            <thead>
                              <tr>
                                <th scope="col"><p align = "center">Unidade</p></th>
                                <th scope="col"><p align = "center">Trabalhos</p></th>
                                <th scope="col"><p align = "center">Esforço</p></th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for item in esforco_unid %}
                                {% if item.planoEntregasEntregasId ==  e.planoEntregasEntregasId%}
                                  <tr>
                                    <td><p align = "center">{{item.undSiglaCompleta}}</p></td>
                                    <td><p align = "center">{{item.trabs_qtd}}</p></td>
                                    <td><p align = "center">{{(item.esforco_soma / item.qtd_pessoas)|decimal_com_virgula}} %</p></td>
                                  </tr>  
                                {% endif %}
                              {% endfor %}    
                            </tbody>
                          </table>  


                        </div>
                        <div class="modal-footer">
                        </div>
                      </div>
                    </div>
                  </div>

          {% endif %}
          </div>
        </div>  
        #}

        <br>

        <div class="row justify-content-center">

          <div class="col-10">
            {% if e.progresso_realizado != None %}
              Progresso da Entrega
              <div class="progress" style="height: 25px;">
                <div class="progress-bar bg-info" role="progressbar" aria-label="Cumprimento" style="width: {{ e.progresso_realizado|round|int }}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                  <b><span class="text-dark">{{ e.progresso_realizado|round|int }}%</span></b>
                </div>
              </div>
            {% endif %}

          </div>

        </div>

      </div>

      <div class="modal-footer"></div>
             
    </div>

  {% endfor %}


</div>
{% endblock %}

project/entregas/templates/consulta_pts.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('entregas.lista_pe', lista = 'Todas', coord = '**')}}">Planos de Entregas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>PTs vinculados a um PE</span></li>
    </ul>
  </div>
</div>

<div class="container">
  
  <h4>Lista de Planos de Trabalho vinculados ao Plano de Entregas: <b>{{pe.sigla}} - {{pe.status}} -  {{pe.data_inicio.strftime('%d/%m/%Y')}} a {{pe.data_fim.strftime('%d/%m/%Y')}}</b></h4>

<caption>
  <div class="row">
      <div class="col-8">
        <p>Lista de <b>{{quantidade}}</b> Planos de Trabalho</p>
      </div>
  </div>
</caption>

<div style="overflow-y:auto">
  <table id="table"
              data-toggle="table"
              data-filter-control="true"
              data-show-search-clear-button="true"
              data-sortable="true"
              classes="table-sm"
              data-show-columns="true"
              data-show-columns-toggle-all="true"
              class="table table-striped table-hover table-sm">
          <caption>Planos de Trabalho</caption>

    <thead>
      <tr>
        <th scope="col"><p align = "center">#</p></th>
        <th scope="col" data-field="Pessoa" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Pessoa</p></th>
        <th scope="col" data-field="Unidade" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Unidade</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Início</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Fim</p></th>
        <th scope="col" data-field="Forma" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Forma</p></th>
        <th scope="col" data-field="Status" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Status</p></th>
        <th scope="col"><p align = "center"><abbr title="Carga Horária">C.H.</abbr></p></th>
        <th scope="col"><p align = "center">Avaliações</p></th>
      </tr>
    </thead>

    <tbody>
      {% for p in planos_trab_pe %}
      <tr>
        <th scope="row"><p align = "center"> 
          {{planos_trab_pe.index(p) + 1}} </p>
        </th>
        <td><p align = "center"> {{p.nome}} </p></td>
        <td><p align = "center"> {{p.sigla}} </p></td>
        <td><p align = "center"> {{p.data_inicio.strftime('%d/%m/%Y')}} </p></td>
        <td><p align = "center"> {{p.data_fim.strftime('%d/%m/%Y')}} </p></td> 
        <td><p align = "center"> {{p.forma}} </p></td>
        <td><p align = "center"> 
            {% if p.status == 'ATIVO' %}
              <span class="text-primary">{{p.status}}</span>
            {% elif p.status == 'AGUARDANDO_ASSINATURA' %}
              <span class="text-warning">{{p.status}}</span>
            {% elif p.status == 'CONCLUIDO' and p.qtd_aval > 0 %}
              <span class="text-success">{{p.status}}</span>
            {% elif p.status == 'CONCLUIDO' and p.nota == 0 %}
              <span class="text-danger">{{p.status}}</span> 
            {% elif p.descricao == 'CANCELADO' %}
              <span class="text-info">{{p.status}}</span>        
            {% else %} 
              {{p.status}}  
            {% endif %} 
          </p> 
        </p></td>
        <td><p align = "center"> {{p.carga_horaria|decimal_com_virgula}} ({{p.forma_contagem_carga_horaria}}) </p></td>  

        {% if p.qtd_aval != None and p.qtd_aval > 0 %}
            <td><p align = "center">
              {{p.qtd_aval}}
            {# 
            <a style="text-decoration: none" href="#" data-bs-toggle='modal' data-bs-target='#aval_modal{{planos_trab_pe.index(p) + 1}}'>class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
              {{p.qtd_aval}}</a>

               <!-- modal visualização da avaliação do PE  -->
              <div class="modal fade" tabindex="-1" role="dialog" id="aval_modal{{planos_trab_pe.index(p) + 1}}">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Avaliação do PT {{planos_trab_pe.index(p) + 1}}</h4>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <ul class="small list-group">
                        {% for a in avaliacoes_lista %}
                          {% if a.planoTrabalhoId == p.planos_trab_pe %}
                            <li class="list-group-item">
                              <p>Parecer: <b>{{ a.descricao}}</b></p>
                              <p>Data: <b>{{ a.dataAvalia.strftime('%d/%m/%Y') }}</b></p>
                              <p>Justificativa: <b>{{ a.relato }}</b></p>
                            </li>  
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </div>
                    <div class="modal-footer">
                    </div>
                  </div>
                </div>
              </div>
              #}

            </p></td>
        {% else %}
            <td><p align = "center">SEM AVALIAÇÃO</p></td>
        {% endif%}
        
      </tr>
      {% endfor %}
    </tbody>

  </table>

</div>

</div>
{% endblock %}

project/entregas/templates/lista_pe.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Planos de Entrega</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">
<div class="jumbotron">

  <div class="row">
    <div class="col-9">
      <h4>Planos de Entregas</h4>
    </div>
    <div class="col-2">
      <form class="needs-validation" method='POST' >

        {{ form.hidden_tag() }}

        <div class="row justify-content-around">

          {{ form.submit(class="br-button secondary mr-3") }}

        </div>

      </form>
    </div>
  </div>

  <caption>
    <div class="row">
        <div class="col-8">
          <p>Lista de <b>{{quantidade}}</b> planos. 
        </div>
    </div>
  </caption>

  <div class="container" style="overflow-y:auto;">

    <table id="table"
          data-toggle="table"
          data-filter-control="true"
          data-show-search-clear-button="true"
          data-sortable="true"
          classes="table-sm"
          data-show-columns="true"
          data-show-columns-toggle-all="true"
          class="table table-striped table-hover table-sm">
      <caption>Planos de Entregas</caption>
      <thead>
        <tr>
          <th scope="col"><p align = "center">#</p></th>
          <th scope="col" data-field="Unidade" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Unidade</p></th>
          <th scope="col" data-field="Status" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Status</p></th>
          <th scope="col" data-sortable="true"><p align = "center">Início</p></th>
          <th scope="col" data-sortable="true"><p align = "center">Fim</p></th>
          <th scope="col"><p align = "center">Entregas</p></th>
          <th scope="col"><p align = "center">&emsp;PTs&emsp;</p></th>
          <th scope="col"><p align = "center">Avaliação</p></th>
        </tr>
      </thead>
      <tbody>

        {% for p in planos_entregas_todos %}

        <tr>
          <th scope="row"><p align = "center"> 
            {{planos_entregas_todos.index(p) + 1}}
          </p></th>
          <td><p align = "center"> 
              {% if p.sigla_pai %}
                {{p.sigla_pai}}/{{ p.sigla }}
              {% else %}
                {{ p.sigla }}
              {% endif %}   
              
              {% if p.deleted_at %}
                ({{p.deleted_at.strftime('%d/%m/%Y')}})
              {% endif %}

          </p></td>
          <td><p align = "center">
              {% if p.vencido == 's' and p.status == 'ATIVO' %} 
                <span class="text-danger"><b>{{p.status}}</b></span>
              {% elif p.status == 'INCLUIDO' %}
                <span class="text-primary">{{p.status}}</span>
              {% elif p.status == 'CONCLUIDO' %}
                <span class="text-success">{{p.status}}</span>  
              {% elif p.status == 'HOMOLOGANDO' %}
                <span class="text-warning">{{p.status}}</span>  
              {% else %}
                <span class="text-dark">{{p.status}}</span>
              {% endif %}
          
          </p></td>
          <td><p align = "center"> {{p.data_inicio.strftime('%d/%m/%Y')}} </p></td>
          <td><p align = "center"> {{p.data_fim.strftime('%d/%m/%Y')}} </p></td>

         <td><p align = "center"> 
                {% if p.qtd_entregas == None %}
                  0
                {% else %}
                  <a style="text-decoration: none" href="{{url_for('entregas.consulta_entregas',peId=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
                     {{p.qtd_entregas}} </a> 
                {% endif %}
     
          </p></td>

          <td>  
            <p align = "center"> 
              {% if p.qtd_planos_trab == None or p_qtd_planos_trab == 0 %}
                Não há
              {% else %}
                <a style="text-decoration: none" href="{{url_for('entregas.consulta_pts',peId=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
                  {{p.qtd_planos_trab}}</a>
              {% endif %}

            </p>
          </td> 
          
          {% if p.nota != None %}
            <td><p align = "center">

              <a href="#" data-bs-toggle='modal' data-bs-target='#aval_modal{{planos_entregas_todos.index(p) + 1}}'><i class="fa-solid fa-check"></i></a></abbr>
              
                {# modal visualização da avaliação do PE #}
                <div class="modal fade" tabindex="-1" role="dialog" id="aval_modal{{planos_entregas_todos.index(p) + 1}}">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Avaliação do PE {{planos_entregas_todos.index(p) + 1}}</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <p>Data: <b>{{ p.data_avaliacao.strftime('%d/%m/%Y') }}</b></p>
                        <p>Parecer: <b>{{ p.nota }}</b></p>
                        <p>Justificativa: <b>{{ p.justificativa }}</b></p>
                      </div>
                      <div class="modal-footer">
                      </div>
                    </div>
                  </div>
                </div>                      

            </p></td>
            
          {% else %}
            <td>
              
              <p align = "center">
                Não há
              </p>
             
            </td>
            
          {% endif%}
              
        </tr>

        {% endfor %}

      </tbody>
    </table>

  </div>

</div>
</div>

{% endblock %}