project/trabalhos/views.py
"""
.. topic:: trabalhos (views)

    Planos de Trabalho.

.. topic:: Ações relacionadas a Planos de Trabalho



"""

# views.py dentro da pasta trabalhos

from flask import render_template, Blueprint, send_from_directory, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import func, case, literal_column
from sqlalchemy.sql import label
from sqlalchemy.orm import aliased
from project import db, app
from project.models import Unidades, Pessoas, planos_trabalhos, planos_trabalhos_consolidacoes, planos_trabalhos_entregas, atividades,\
                           avaliacoes, tipos_modalidades, planos_entregas_entregas

from project.trabalhos.forms import CSV_Form

import os, csv

from datetime import datetime as dt

import random
import string

trabalhos = Blueprint("trabalhos",__name__,template_folder='templates')


def ponto_por_virgula(valor):
    if valor != None and valor != '':
        return str(valor).replace('.',',')
    else:
        return 'N.I.'            

def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(length))


# lista dos planos de trabalho da unidade
@trabalhos.route('<lista>/lista_pts',methods=['GET','POST'])
@login_required
def lista_pts(lista):

    """
        +----------------------------------------------------------------------+
        |Lista os planos de trabalho, bem como registros                       |
        |associados.                                                           |
        |                                                                      |
        +----------------------------------------------------------------------+
    """
    
    
    hoje = dt.today()


    #subquery que conta trabalhos em cada plano de trabalho 
    trabalhos = db.session.query(atividades.plano_trabalho_id,
                                label('qtd_trabalhos',func.count(atividades.id)))\
                          .filter(atividades.deleted_at == None)\
                          .group_by(atividades.plano_trabalho_id)\
                          .subquery() 
                        
    #subquery que conta avaliações em pt a partir de plano_trabalho_consolidacao
    avaliacoes_pt = db.session.query(planos_trabalhos_consolidacoes.plano_trabalho_id,
                                     label('qtd_aval',func.count(avaliacoes.id)))\
                              .join(avaliacoes, avaliacoes.plano_trabalho_consolidacao_id == planos_trabalhos_consolidacoes.id)\
                              .filter(avaliacoes.data_avaliacao <= hoje)\
                              .group_by(planos_trabalhos_consolidacoes.plano_trabalho_id)\
                              .subquery()                                                                                                                           
    
    if lista == 'Todos':
        lista = '%'
    
    planos_trabalho_lista = db.session.query(planos_trabalhos.id,
                                            planos_trabalhos.data_inicio,
                                            planos_trabalhos.data_fim,
                                            planos_trabalhos.carga_horaria,
                                            planos_trabalhos.forma_contagem_carga_horaria,
                                            planos_trabalhos.status,
                                            label('forma',tipos_modalidades.nome),
                                            planos_trabalhos.data_envio_api_pgd,
                                            Pessoas.nome,
                                            Unidades.sigla,
                                            label('situacao',planos_trabalhos.status),
                                            label('vencido',case((planos_trabalhos.data_fim < hoje, literal_column("'s'")), else_=literal_column("'n'"))),
                                            trabalhos.c.qtd_trabalhos,
                                            avaliacoes_pt.c.qtd_aval)\
                                    .filter(planos_trabalhos.deleted_at == None,
                                            planos_trabalhos.status.like(lista))\
                                    .join(Pessoas, Pessoas.id == planos_trabalhos.usuario_id)\
                                    .join(Unidades, Unidades.id == planos_trabalhos.unidade_id)\
                                    .join(tipos_modalidades, tipos_modalidades.id == planos_trabalhos.tipo_modalidade_id)\
                                    .order_by(planos_trabalhos.status,Unidades.sigla,Pessoas.nome,planos_trabalhos.data_inicio)\
                                    .outerjoin(trabalhos, trabalhos.c.plano_trabalho_id == planos_trabalhos.id)\
                                    .outerjoin(avaliacoes_pt, avaliacoes_pt.c.plano_trabalho_id == planos_trabalhos.id)\
                                    .all()

    quantidade = len(planos_trabalho_lista)                         
 
    form = CSV_Form()

    if form.validate_on_submit():

        csv_caminho_arquivo = os.path.normpath('/app/project/static/planos_trabalho.csv')
        
        dados_a_escrever = [[p.nome, p.sigla, p.data_inicio, p.data_fim, p.forma, p.situacao, str(p.carga_horaria) +'('+p.forma_contagem_carga_horaria+')', p.qtd_trabalhos, p.qtd_aval] for p in planos_trabalho_lista]

        header = ['Pessoa', 'Unidade','Início','Fim', 'Forma', 'Situação', 'C.H.', 'Trabalhos', 'Avaliações']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', 'planos_trabalho.csv')

        return redirect(url_for('static', filename = 'planos_trabalho.csv'))    
    
    return render_template ('lista_pts.html', planos_trabalho_lista = planos_trabalho_lista, 
                                              quantidade = quantidade,
                                              lista = lista,
                                              form = form)



## lista trabalhos (atividades) de um plano de trabalho
@trabalhos.route('/<ptId>/consulta_trabalhos')
@login_required
def consulta_trabalhos(ptId):
    """
    +---------------------------------------------------------------------------------------+
    |Lista os trabalhos (atividades) que foram registrados em um plano de trabalho.         |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    # resgata registros em atividades
    trabalhos = db.session.query(atividades.descricao,
                                 label('entrega',planos_entregas_entregas.descricao),
                                 atividades.status,
                                 atividades.carga_horaria,
                                 atividades.progresso,
                                 atividades.data_inicio,
                                 atividades.data_entrega)\
                          .filter(atividades.deleted_at == None,
                                  atividades.plano_trabalho_id == ptId)\
                          .outerjoin(planos_trabalhos_entregas, planos_trabalhos_entregas.id == atividades.plano_trabalho_entrega_id)\
                          .outerjoin(planos_entregas_entregas, planos_entregas_entregas.id == planos_trabalhos_entregas.plano_entrega_entrega_id)\
                          .all()

    quantidade = len(trabalhos)                    

    return render_template('consulta_trabalhos.html', trabalhos=trabalhos,
                                                      quantidade = quantidade)


## lista avaliações de um plano de trabalho
@trabalhos.route('/<ptId>/consulta_avaliacoes')
@login_required
def consulta_avaliacoes(ptId):
    """
    +---------------------------------------------------------------------------------------+
    |Lista as avaliações que foram registrados em um plano de trabalho.                     |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    hoje = dt.today()
    
    avaliados = aliased(Pessoas)

    # avaliações de um pt
    avaliacoes_pt = db.session.query(planos_trabalhos_consolidacoes.plano_trabalho_id,
                                     avaliacoes.data_avaliacao,
                                     avaliacoes.nota,
                                     label('avaliador',Pessoas.nome),
                                     label('avaliado',avaliados.nome),
                                     planos_trabalhos.data_inicio,
                                     planos_trabalhos.data_fim,
                                     avaliacoes.recurso)\
                              .join(avaliacoes, avaliacoes.plano_trabalho_consolidacao_id == planos_trabalhos_consolidacoes.id)\
                              .join(planos_trabalhos, planos_trabalhos.id == planos_trabalhos_consolidacoes.plano_trabalho_id)\
                              .outerjoin(Pessoas, Pessoas.id == avaliacoes.avaliador_id)\
                              .join(avaliados, avaliados.id == planos_trabalhos.usuario_id)\
                              .filter(avaliacoes.data_avaliacao <= hoje,
                                      avaliacoes.deleted_at == None,
                                      planos_trabalhos_consolidacoes.plano_trabalho_id == ptId)\
                              .all()
                              
    quantidade = len(avaliacoes_pt)                    

    return render_template('consulta_avaliacoes.html', avaliacoes_pt=avaliacoes_pt,

project/trabalhos/templates/consulta_avaliacoes.html
{% extends "template_gov.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">

  <h4>Avaliações no Plano de Trabalho selecionado</h4>

  <caption>
    <div class="row">
        <div class="col">
          {% if quantidade == 1 %}
            <p>Lista de <b>{{quantidade}}</b> avaliação. </p>
          {% else %}
            <p>Lista de <b>{{quantidade}}</b> avaliações. </p>
          {% endif %}
        </div>
    </div>
  </caption>

  <div class="container" style="overflow-y:auto; height:400px">

    <table class="table table-striped table-hover table-sm">
      <caption>Avaliações</caption>
      <thead>
        <tr>
          <th scope="col"><p align = "center">#</p></th>
          <th scope="col"><p align = "center">Ini.-Fim do PT</p></th>
          <th scope="col"><p align = "center">Data</p></th>
          <th scope="col"><p align = "center">Nota</p></th>
          <th scope="col"><p align = "left">Avaliador</p></th>
          <th scope="col"><p align = "left">Avaliado</p></th>
          <th scope="col"><p align = "center">Recurso</p></th>
        </tr>
      </thead>
      <tbody>

        {% for a in avaliacoes_pt %}

        <tr>
          
          <th scope="row"><p align = "center">{{avaliacoes_pt.index(a) + 1}}</p></th>
          <td><p align = "center"> {{a.data_inicio.strftime('%d/%m/%Y')}} - {{a.data_fim.strftime('%d/%m/%Y')}}  </p></td>
          <td><p align = "center"> {{a.data_avaliacao.strftime('%d/%m/%Y')}} </p></td>
          <td><p align = "center"> {{a.nota.split('"')[2][:-1]}} </p></td>
          <td><p align = "left"> {{a.avaliador}} </p></td>
          <td><p align = "left"> {{a.avaliado}} </p></td>
          <td><p align = "center"> 
            {% if a.recurso != None %}
              {{a.recurso}}            
            {% else %}
              NÃO HÁ
            {% endif %}
          </p></td>
        </tr>

        {% endfor %}

      </tbody>
    </table>

  </div>

</div>

</div>
{% endblock %}

project/trabalhos/templates/consulta_trabalhos.html
{% extends "template_gov.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">

  <h4>Trabalhos (atividades) no Plano de Trabalho selecionado</h4>

  <caption>
    <div class="row">
        <div class="col">
          <p>Lista de <b>{{quantidade}}</b> trabalho(s). </p>
        </div>
    </div>
  </caption>

  <div class="container" style="overflow-y:auto; height:400px">

    <table class="table table-striped table-hover table-sm">
      <caption>Trabalhos</caption>
      <thead>
        <tr>
          <th scope="col"><p align = "center">#</p></th>
          <th scope="col"><p align = "center">Entrega</p></th>
          <th scope="col"><p align = "left">Descrição</p></th>
          {# <th scope="col"><p align = "left">C.H.</p></th> #} 
          <th scope="col"><p align = "center">Status</p></th>
          <th scope="col"><p align = "center">% progresso</p></th>
          <th scope="col"><p align = "center">Início</p></th>
          <th scope="col"><p align = "left">Fim</p></th>
        </tr>
      </thead>
      <tbody>

        {% for t in trabalhos %}

        <tr>
          
          <th scope="row"><p align = "center">{{trabalhos.index(t) + 1}}</p></th>
          <td><p align = "center"> 
            {% if t.entrega == None or t.entrega == '' %}
              Não há
            {% else %}  
              {{t.entrega}}
            {% endif %}   
          </p></td>
          <td><p align = "left"> {{t.descricao}} </p></td>
          {# <td><p align = "center"> {{t.carga_horaria}} </p></td> #}
          <td><p align = "center"> 
            {% if t.status == 'INCLUIDO' %}
              <span class="text-primary">{{t.status}}</span>
            {% elif t.status == 'CONCLUIDO' %}
              <span class="text-success">{{t.status}}</span>  
            {% elif t.status == 'PAUSADO' %}
              <span class="text-warning">{{t.status}}</span>  
            {% else %}
              <span class="text-dark">{{t.status}}</span>
            {% endif %} </p></td>
          <td><p align = "center"> {{t.progresso|decimal_com_virgula}} </p></td>
          <td><p align = "center"> {{t.data_inicio.strftime('%d/%m/%Y')}} </p></td>
          <td><p align = "center"> {{t.data_entrega.strftime('%d/%m/%Y')}} </p></td>
        </tr>

        {% endfor %}

      </tbody>
    </table>

  </div>

</div>

</div>
{% endblock %}

project/trabalhos/templates/lista_pts.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Lista de Planos de Trabalho 
        {% if lista == 'Enviado para aceite' %}
          enviado(s) para aceite
        {% elif lista == 'solic_pend' %}
          com solicitaçõe(s) pendente(s)
        {% elif lista == 'para_avaliar' %}
          que aguarda(m) avaliação pela chefia
        {% elif lista == '%' %}
          em todas as situações   
        {% endif %}
      </span></li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-9">
      <h4>Lista de Planos de Trabalho</h4>
    </div>
    <div class="col-2">
      <form class="needs-validation" method='POST' >

        {{ form.hidden_tag() }}

        <div class="row justify-content-around">

          {{ form.submit(class="br-button secondary mr-3") }}

        </div>

      </form>
    </div>
  </div>

<caption>
  <div class="row">
      <div class="col-10">
        <p>Lista de <b>{{quantidade}}</b> Planos de Trabalho
          {% if lista == 'AGUARDANDO_ASSINATURA' %}
            aguardando assinatura
          {% elif lista == 'solic_pend' %}
            com solicitaçõe(s) pendente(s)
          {% elif lista == 'para_avaliar' %}
            que aguarda(m) avaliação pela chefia
          {% elif lista == 'recurso' %}
            com recurso sobre avaliação  
          {% elif lista == '%' %}
            em todas as situações  
          {% else %}
            {{lista}}  
          {% endif %}    
        </p>
      </div>
  </div>
</caption>

<div style="overflow-y:auto">
  <table id="table"
              data-toggle="table"
              data-filter-control="true"
              data-show-search-clear-button="true"
              data-sortable="true"
              classes="table-sm"
              data-show-columns="true"
              data-show-columns-toggle-all="true"
              class="table table-striped table-hover table-sm">
          <caption>Planos de Trabalho</caption>

    <thead>
      <tr>
        <th scope="col"><p align = "center">#</p></th>
        <th scope="col" data-field="Pessoa" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Pessoa</p></th>
        <th scope="col" data-field="Unidade" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Unidade</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Início</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Fim</p></th>
        <th scope="col" data-field="Forma" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Forma</p></th>
        <th scope="col" data-field="Situação" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Situação</p></th>
        <th scope="col"><p align = "center"><abbr title="Carga Horária Diária">C.H.</abbr></p></th>
        <th scope="col"><p align = "center"><abbr title="Lista dos trabalhos deste PT">Trabalhos</abbr></p></th>
        <th scope="col"><p align = "center">Avaliações</p></th>
      </tr>
    </thead>

    <tbody>
      {% for p in planos_trabalho_lista %}
      <tr>
        <th scope="row"><p align = "center"> 
          {#
          <a class="card-title" href="{{url_for('trabalhos.ver_pt',ptId=p.planoTrabalhoId)}}">
          <abbr title="Clique aqui para ver detalhes do Plano">
          {{planos_trabalho_lista.index(p) + 1}} </abbr></a>
          #}
          {{planos_trabalho_lista.index(p) + 1}}
        </p>
        </th>
        <td><p align = "center"> {{p.nome}} </p></td>
        <td><p align = "center"> {{p.sigla}} </p></td>
        <td><p align = "center"> {{p.data_inicio.strftime('%d/%m/%Y')}} </p></td>
        <td><p align = "center"> {{p.data_fim.strftime('%d/%m/%Y')}} </p></td> 
        <td><p align = "center"> {{p.forma}} </p></td>
        <td><p align = "center">  
            {% if p.vencido == 's' and p.status == 'ATIVO' %} 
              <span class="text-danger"><b>{{p.status}}</b></span>
            {% elif p.status == 'INCLUIDO' %}
              <span class="text-primary">{{p.status}}</span>
            {% elif p.status == 'AVALIADO' %}
              <span class="text-success">{{p.status}}</span>  
            {% elif p.status == 'AGUARDANDO_ASSINATURA' %}
              <span class="text-warning">{{p.status}}</span>  
            {% else %}
              <span class="text-dark">{{p.status}}</span>
            {% endif %}
        </p></td>
        <td><p align = "center"> {{p.carga_horaria|decimal_com_virgula}} ({{p.forma_contagem_carga_horaria}}) </p></td>  
        <td><p align = "center"> 
          {% if p.qtd_trabalhos != None %}
            <a style="text-decoration: none" href="{{url_for('trabalhos.consulta_trabalhos',ptId=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
              {{p.qtd_trabalhos}} </a>            
          {% else %}
            Não há
          {% endif %}   
        </p></td> 
        <td><p align = "center">
          {% if p.qtd_aval != None %}
            <a style="text-decoration: none" href="{{url_for('trabalhos.consulta_avaliacoes',ptId=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
              {{ p.qtd_aval }}   </a>
        {% else %}
          Não há
        {% endif%}
      </p></td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

</div>

</div>
{% endblock %}

project/trabalhos/templates/lista_trabalhos_pt.html
{% extends "template_gov.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">

  <h4>Trabalhos no Plano de Trabalho informado</h4>

  <caption>
    <div class="row">
        <div class="col">
          <p>Lista de <b>{{qtd_trabalhos}}</b> trabalho(s). </p>
        </div>
    </div>
  </caption>

  <div class="container" style="overflow-y:auto; height:400px">

    <table class="table table-striped table-hover table-sm">
      <caption>Trabalhos</caption>
      <thead>
        <tr>
          <th scope="col"><p align = "center">#</p></th>
          <th scope="col"><p align = "center">Entrega</p></th>
          <th scope="col"><p align = "left">Descrição</p></th>
          <th scope="col"><p align = "center">Situação</p></th>
          <th scope="col"><p align = "center">% esforço</p></th>
          <th scope="col"><p align = "center">Demandas</p></th>
          <th scope="col"><p align = "left">Relato</p></th>
        </tr>
      </thead>
      <tbody>

        {% for t in trabalhos %}

        <tr>
          
          <th scope="row"><p align = "center">{{trabalhos.index(t) + 1}}</p></th>
          <td><p align = "center"> {{t.nome}} </p></td>
          <td><p align = "left"> {{t.descricao}} </p></td>
          <td><p align = "center"> {{t.sit}} </p></td>
          <td><p align = "center"> {{t.percentualEsforco}} </p></td>
          <td><p align = "center"> {{t.qtd_demandas}} </p></td>
          <td><p align = "left"> {% if t.relatoEntrega == None %}N.I.{% else %} {{t.relatoEntrega}} {% endif %}</p></td>
        </tr>

        {% endfor %}

      </tbody>
    </table>

  </div>

</div>

</div>
{% endblock %}