project/envios/views.py
"""
.. topic:: envios (views)

    Informações sobre envios.

"""

# views.py dentro da pasta envios

from flask import render_template, url_for, send_from_directory, redirect, Blueprint
from flask_login import current_user, login_required
from sqlalchemy import cast, Date
from sqlalchemy.sql import label
from sqlalchemy.orm import aliased
from project import db, app
from project.models import Pessoas, planos_entregas,\
                           planos_trabalhos, envio_itens
from project.envios.forms import CSV_Form

from datetime import datetime as dt

import csv, os

envios = Blueprint("envios",__name__,template_folder='templates')    


## envios não realizados

@envios.route('/envios_insucesso')
@login_required
def envios_insucesso():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta tela para escolha do tipo de envio mal sucedido.                             |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """                           

    return render_template('envio.html')

@envios.route('/envios_insucesso_pe',methods=['GET','POST'])
@login_required
def envios_insucesso_pe():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta dados dos PEs cujo envio não foi bem sucedido.                               |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """                    

    tipo = 'pe'

    envios_sem_sucesso = db.session.query(envio_itens.id,
                                          envio_itens.tipo,
                                          envio_itens.uid,
                                          envio_itens.sucesso,
                                          envio_itens.erros,
                                          envio_itens.created_at,
                                          planos_entregas.nome,
                                          planos_entregas.status)\
                            .outerjoin(planos_entregas, planos_entregas.id == envio_itens.uid)\
                            .filter(envio_itens.sucesso == 0,
                                    envio_itens.tipo == 'entrega')\
                            .order_by(envio_itens.created_at.cast(Date).desc(),
                                      planos_entregas.nome)\
                            .all() 
                                          

    quantidade = len(envios_sem_sucesso)

    form = CSV_Form()

    if form.validate_on_submit():
        
        csv_caminho_arquivo = os.path.normpath('/app/project/static/'+ tipo +'.csv')

        dados_a_escrever = [[e.nome, e.status, e.erros, e.created_at] for e in envios_sem_sucesso]
        
        header = ['Nome', 'Status','Erro','Data']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', tipo +'.csv')

        return redirect(url_for('static', filename = tipo +'.csv'))
            

    return render_template('lista_envios_sem_sucesso.html', 
                                            envios_sem_sucesso = envios_sem_sucesso,
                                            quantidade = quantidade,
                                            tipo = tipo,
                                            form = form)

@envios.route('/envios_insucesso_pt',methods=['GET','POST'])
@login_required
def envios_insucesso_pt():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta dados dos PTs cujo envio não foi bem sucedido.                               |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """    

    tipo = 'pt'                
                                                                                                           
    donos_pts = aliased(Pessoas)                                                                          
        
    envios_sem_sucesso = db.session.query(envio_itens.id,
                                          envio_itens.tipo,
                                          envio_itens.uid,
                                          envio_itens.sucesso,
                                          envio_itens.erros,
                                          envio_itens.created_at,
                                          planos_trabalhos.numero,
                                          label('pt_dono',donos_pts.nome),
                                          label('status_pt',planos_trabalhos.status))\
                            .outerjoin(planos_trabalhos, planos_trabalhos.id == envio_itens.uid)\
                            .outerjoin(donos_pts, donos_pts.id == planos_trabalhos.usuario_id)\
                            .filter(envio_itens.sucesso == 0,
                                    envio_itens.tipo == 'trabalho')\
                            .order_by(envio_itens.created_at.cast(Date).desc(),
                                      donos_pts.nome)\
                            .all() 
                                          

    quantidade = len(envios_sem_sucesso)

    form = CSV_Form()

    if form.validate_on_submit():
        
        csv_caminho_arquivo = os.path.normpath('/app/project/static/'+ tipo +'.csv')

        dados_a_escrever = [[str(e.numero) +' - '+e.pt_dono, e.status_pt, e.erros, e.created_at] for e in envios_sem_sucesso]
        
        header = ['Nº - Nome', 'Status','Erro','Data']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', tipo +'.csv')

        return redirect(url_for('static', filename = tipo +'.csv'))
            

    return render_template('lista_envios_sem_sucesso.html', 
                                            envios_sem_sucesso = envios_sem_sucesso,
                                            quantidade = quantidade,
                                            tipo = tipo,
                                            form = form)


@envios.route('/envios_insucesso_par',methods=['GET','POST'])
@login_required
def envios_insucesso_par():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta dados dos Participantes cujo envio não foi bem sucedido.                     |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """  

    tipo = 'par'                  
                                                                                                                   
    envios_sem_sucesso = db.session.query(envio_itens.id,
                                          envio_itens.tipo,
                                          envio_itens.uid,
                                          envio_itens.sucesso,
                                          envio_itens.erros,
                                          envio_itens.created_at,
                                          label('participante_nome',Pessoas.nome),
                                          Pessoas.matricula)\
                            .outerjoin(Pessoas, Pessoas.id == envio_itens.uid)\
                            .filter(envio_itens.sucesso == 0,
                                    envio_itens.tipo == 'participante')\
                            .order_by(envio_itens.created_at.cast(Date).desc(),
                                      Pessoas.nome)\
                            .all() 
                                          
    quantidade = len(envios_sem_sucesso)

    form = CSV_Form()

    if form.validate_on_submit():
        
        csv_caminho_arquivo = os.path.normpath('/app/project/static/'+ tipo +'.csv')

        dados_a_escrever = [[e.participante_nome, e.matricula, e.erros, e.created_at] for e in envios_sem_sucesso]
        
        header = ['Nome', 'Matrícula','Erro','Data']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', tipo +'.csv')

        return redirect(url_for('static', filename = tipo +'.csv'))    
        
    return render_template('lista_envios_sem_sucesso.html', 
                                            envios_sem_sucesso = envios_sem_sucesso,
                                            quantidade = quantidade,
                                            tipo = tipo,
                                            form = form)

project/envios/templates/envio.html
{% extends "template_gov.html" %}
{% block content %}


  <div class="col mb-5">
    <div class="br-breadcrumb">
      <ul class="crumb-list">
        <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Escolher Tipo</span></li>
      </ul>
    </div>
  </div>


    <div class="row mt-5">
      <div class="d-flex justify-content-center  flex-wrap">
    

        {% with 
          icon="fa-list", 
          title="Planos de Entregas",
          description="Lista os envios mal sucedidos de Planos de Entregas",
          link=url_for('envios.envios_insucesso_pe')
        %}
          {% include "card_menu.html" %}
        {% endwith %}

        {% with 
          icon="fa-list-check", 
          title="Planos de Trabalho",
          description="Lista os envios mal sucedidos de Planos de Trabalho",
          link=url_for('envios.envios_insucesso_pt')
        %}
          {% include "card_menu.html" %}
        {% endwith %}

        {% with 
          icon="fa-user-times", 
          title="Participantes",
          description="Lista os envios mal sucedidos de Participantes",
          link=url_for('envios.envios_insucesso_par')
        %}
          {% include "card_menu.html" %}
        {% endwith %}

      </div>
    </div>

{% endblock %}

project/envios/templates/lista_envios_sem_sucesso.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('envios.envios_insucesso')}}">Escolher tipo</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>
        {% if tipo == 'par' %}
          Participantes
        {% elif tipo == 'pe' %}
          Planos de Entregas
        {% elif tipo == 'pt' %}
          Planos de Trabalho 
        {% endif %}</span></li>
    </ul>
  </div>
</div>

<div class="container">
<div class="jumbotron">

  <div class="row">
    <div class="col-10">
      <h4>
        {% if tipo == 'par' %}
          Participantes com problema no envio
        {% elif tipo == 'pe' %}
          Planos de Entregas com problema no envio
        {% elif tipo == 'pt' %}
          Planos de Trabalho com problem ano envio 
        {% endif %}
      </h4>
    </div>

    <div class="col-2">

      <form class="needs-validation" method='POST' >

        {{ form.hidden_tag() }}

        <div class="row justify-content-around">

          {{ form.submit(class="br-button secondary mr-3") }}

        </div>

      </form>

    </div>

  </div>

  <caption>
    <div class="row">
        <div class="col-8">
          <p>Lista de <b>{{quantidade}}</b> itens. 
        </div>
    </div>
  </caption>

  <div class="container" style="overflow-y:auto;">

    <table id="table"
          data-toggle="table"
          data-filter-control="true"
          data-show-search-clear-button="true"
          data-sortable="true"
          classes="table-sm"
          data-show-columns="true"
          data-show-columns-toggle-all="true"
          class="table table-striped table-hover table-sm">
      <caption>Envios mal sucedidos</caption>
      <thead>
        <tr>
          <th scope="col"><p align = "center">#</p></th>
          {% if tipo == 'par' %}
            <th scope="col" data-field="Nome" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Nome</p></th>
            <th scope="col"><p align = "center">Matrícula</p></th>
          {% elif tipo == 'pe' %}
            <th scope="col" data-field="Nome" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Nome</p></th>
            <th scope="col"><p align = "center">Status</p></th>
          {% elif tipo == 'pt' %}
            <th scope="col" data-field="Dono" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Nº - Dono</p></th>
            <th scope="col"><p align = "center">Status</p></th> 
          {% endif %} 
          <th scope="col" data-field="Erro" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Erro</p></th>
          <th scope="col" data-sortable="true"><p align = "center">Data</p></th>
        </tr>
      </thead>
      <tbody>

        {% for e in envios_sem_sucesso %}

        <tr>
          <th scope="row"><p align = "center"> 
            {{envios_sem_sucesso.index(e) + 1}}
          </p></th>
          <td><p align = "center"> 
              {% if e.tipo == 'participante' %}
                {{e.participante_nome}}
              {% elif e.tipo == 'entrega' %}
                {{ e.nome }}
              {% elif e.tipo == 'trabalho' %}
                {{ e.numero }} - {{ e.pt_dono }}  
              {% endif %}   
          </p></td>
          <td><p align = "center">
              {% if e.tipo == 'participante' %}
                {% if e.matricula == None %}
                  N.I.
                {% else %}  
                  {{e.matricula}}
                {% endif %}  
              {% elif e.tipo == 'entrega' %}
                {{ e.status }}
              {% elif e.tipo == 'trabalho' %}
                {{ e.status_pt }}  
              {% endif %}  
          </p></td>
          <td><p align = "center"> 
            {{ e.erros }}
          </p></td>
          <td><p align = "center"> 
            {{ e.created_at.strftime('%d/%m/%Y') }}
          </p></td>

        </tr>

        {% endfor %}

      </tbody>
    </table>

  </div>

</div>
</div>

{% endblock %}