project/pessoas/views.py
"""
.. topic:: Pessoas (views)

    As Pessoas são os servidores lotados na intituição.
    
.. topic:: Ações relacionadas à gestão de pessoas

    * lista_pessoas: Lista das pessoas da instituição
    * lista_pessoas_filtro: Procura pessoas na instituição 

"""

# views.py na pasta pessoas

import os, csv

from flask import render_template, Blueprint, request, redirect, send_from_directory, url_for
from flask_login import current_user, login_required

from sqlalchemy.sql import label
from sqlalchemy import func, distinct

from project import db
from project.models import Unidades, unidades_integrantes, Pessoas, perfis, unidades_integrantes_atribuicoes, planos_trabalhos,\
                           planos_trabalhos_entregas, planos_entregas_entregas, tipos_modalidades, planos_trabalhos_consolidacoes,\
                           avaliacoes
                            
from project.pessoas.forms import PesquisaForm, CSV_Form


pessoas = Blueprint('pessoas',__name__, template_folder='templates')


 ## lista pessoas da instituição

@pessoas.route('/lista_pessoas',methods=['GET','POST'])
@login_required

def lista_pessoas():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta uma lista das pessoas da instituição.                                        |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    page = request.args.get('page', 1, type=int)    

    tipo = "inst"
    
    # Verifica a quantidade de pessoas para decidir sobre paginação
    
    qtd_pessoas = db.session.query(Pessoas).count()
        
    if qtd_pessoas < 500:
        pag = 500
    else:
        pag = 100
    
    # Lê tabela pessoas

    pessoas_lista = db.session.query(Pessoas.id,
                                     Pessoas.nome,
                                     Pessoas.cpf,
                                     Pessoas.data_nascimento,
                                     Pessoas.matricula,
                                     Pessoas.email,
                                     Unidades.sigla,
                                     unidades_integrantes_atribuicoes.atribuicao,
                                     Pessoas.situacao_funcional,
                                     label('perfil',perfis.nome),
                                     label('qtd_planos_trab',func.count(distinct(planos_trabalhos.id))))\
                                .outerjoin(unidades_integrantes, unidades_integrantes.usuario_id == Pessoas.id)\
                                .outerjoin(unidades_integrantes_atribuicoes, unidades_integrantes_atribuicoes.unidade_integrante_id == unidades_integrantes.id)\
                                .outerjoin(Unidades, Unidades.id == unidades_integrantes.unidade_id)\
                                .join(perfis, perfis.id == Pessoas.perfil_id)\
                                .outerjoin(planos_trabalhos, planos_trabalhos.usuario_id == Pessoas.id)\
                                .filter(Pessoas.deleted_at == None)\
                                .order_by(Pessoas.nome)\
                                .group_by(Pessoas.id,Unidades.sigla,unidades_integrantes_atribuicoes.atribuicao)\
                                .paginate(page=page,per_page=pag)

    quantidade = pessoas_lista.total

    form = CSV_Form()

    if form.validate_on_submit():
        
        csv_caminho_arquivo = os.path.normpath('/app/project/static/pessoas.csv')

        pessoas_csv = db.session.query(Pessoas.id,
                                     Pessoas.nome,
                                     Pessoas.cpf,
                                     Pessoas.data_nascimento,
                                     Pessoas.matricula,
                                     Pessoas.email,
                                     Unidades.sigla,
                                     unidades_integrantes_atribuicoes.atribuicao,
                                     Pessoas.situacao_funcional,
                                     label('perfil',perfis.nome),
                                     label('qtd_planos_trab',func.count(distinct(planos_trabalhos.id))))\
                                .outerjoin(unidades_integrantes, unidades_integrantes.usuario_id == Pessoas.id)\
                                .outerjoin(unidades_integrantes_atribuicoes, unidades_integrantes_atribuicoes.unidade_integrante_id == unidades_integrantes.id)\
                                .outerjoin(Unidades, Unidades.id == unidades_integrantes.unidade_id)\
                                .join(perfis, perfis.id == Pessoas.perfil_id)\
                                .outerjoin(planos_trabalhos, planos_trabalhos.usuario_id == Pessoas.id)\
                                .filter(Pessoas.deleted_at == None)\
                                .order_by(Pessoas.nome)\
                                .group_by(Pessoas.id,Unidades.sigla,unidades_integrantes_atribuicoes.atribuicao)\
                                .all()


        dados_a_escrever = [[p.nome, p.data_nascimento, p.matricula, p.email, p.sigla, p.atribuicao, p.situacao_funcional, p.perfil, p.qtd_planos_trab] for p in pessoas_csv]

        header = ['Nome', 'Data Nasc.','Matrícula','E-mail', 'Unidade', 'Atribuição', 'Situação', 'Perfil', 'PTs']

        with open(csv_caminho_arquivo, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow(header) 
            csv_writer.writerows(dados_a_escrever)

        # o comandinho mágico que permite fazer o download de um arquivo
        send_from_directory('/app/project/static', 'pessoas.csv')

        return redirect(url_for('static', filename = 'pessoas.csv'))


    return render_template('lista_pessoas_gestor.html', pessoas = pessoas_lista,
                                                        quantidade = quantidade,
                                                        qtd_pessoas = qtd_pessoas,
                                                        tipo = tipo,
                                                        form = form)
    
    
## lista pessoas da instituição conforme filtro aplicado

@pessoas.route('/lista_pessoas_filtro', methods=['GET','POST'])
@login_required

def lista_pessoas_filtro():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta uma lista das pessoas da instituição via filtro                              |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    tipo = "pesq"

    form = PesquisaForm() 
    
    unids = db.session.query(Unidades.id,Unidades.sigla)\
                      .filter(Unidades.deleted_at == None)\
                      .order_by(Unidades.sigla).all()
    lista_unids = [(u.id,u.sigla) for u in unids]
    lista_unids.insert(0,('','Todas'))         

    perf = db.session.query(perfis.id, perfis.nome).order_by(perfis.nome).all()
    lista_perf = [(p.id,p.nome) for p in perf]
    lista_perf.insert(0,('','Todos'))
    
    situ = db.session.query(label('situ',Pessoas.situacao_funcional.distinct()))\
                     .order_by(Pessoas.situacao_funcional).all()
    lista_situ = [(s.situ,s.situ) for s in situ]
    lista_situ.insert(0,('','Todas'))

    atrib = db.session.query(label('atrib',unidades_integrantes_atribuicoes.atribuicao.distinct()))\
                      .order_by(unidades_integrantes_atribuicoes.atribuicao).all()
    lista_atrib = [(a.atrib,a.atrib) for a in atrib]
    lista_atrib.insert(0,('','Todas'))

    form.perf.choices    = lista_perf
    form.situ.choices    = lista_situ
    form.atrib.choices   = lista_atrib
    form.unidade.choices = lista_unids

    if form.submit.data and form.validate_on_submit():

        nome_pesq = form.nome.data
        
        if form.situ.data == '':
            p_situ_pattern = '%'
        else:
            p_situ_pattern = '%'+form.situ.data+'%'

        if form.perf.data == '':
            p_perf_pattern = '%'
        else:
            p_perf_pattern = '%'+form.perf.data+'%'
            
        if form.atrib.data == '':
            p_atrib_pattern = '%'
        else:
            p_atrib_pattern = form.atrib.data
            
        if form.unidade.data == '':
            p_unid_pattern = '%'
        else:
            p_unid_pattern = '%'+form.unidade.data+'%'       

        # pega valores utilizados como filtro para exibição na tela da lista
        p_situ  = dict(form.situ.choices).get(form.situ.data)
        p_unid  = dict(form.unidade.choices).get(form.unidade.data) 
        p_perf  = dict(form.perf.choices).get(form.perf.data) 
        p_atrib = dict(form.atrib.choices).get(form.atrib.data) 

        pessoas_lista = db.session.query(Pessoas.id,
                                         Pessoas.nome,
                                         Pessoas.cpf,
                                         Pessoas.data_nascimento,
                                         Pessoas.matricula,
                                         Pessoas.email,
                                         Unidades.sigla,
                                         unidades_integrantes_atribuicoes.atribuicao,
                                         Pessoas.situacao_funcional,
                                         label('perfil',perfis.nome),
                                         label('perfil_id',perfis.id),
                                         label('qtd_planos_trab',func.count(distinct(planos_trabalhos.id))))\
                                  .outerjoin(unidades_integrantes, unidades_integrantes.usuario_id == Pessoas.id)\

project/pessoas/templates/consulta_pts_pessoa.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('pessoas.lista_pessoas')}}">Pessoas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>PTs vinculados a uma pessoa</span></li>
    </ul>
  </div>
</div>

<div class="container">
  
  <h4>Lista de Planos de Trabalho vinculados a <b>{{dados_pessoa.nome}}</b></h4>

<caption>
  <div class="row">
      <div class="col-8">
        <p>Lista de <b>{{quantidade}}</b> Planos de Trabalho</p>
      </div>
  </div>
</caption>

<div style="overflow-y:auto">
  <table id="table"
              data-toggle="table"
              data-filter-control="true"
              data-show-search-clear-button="true"
              data-sortable="true"
              classes="table-sm"
              data-show-columns="true"
              data-show-columns-toggle-all="true"
              class="table table-striped table-hover table-sm">
          <caption>Planos de Trabalho</caption>

    <thead>
      <tr>
        <th scope="col"><p align = "center">#</p></th>
        <th scope="col" data-field="Unidade" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Unidade</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Início</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Fim</p></th>
        <th scope="col" data-field="Forma" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Forma</p></th>
        <th scope="col" data-field="Status" data-filter-control="input" data-sortable="true" data-filter-control-placeholder="Termo de pesquisa..."><p align = "center">Status</p></th>
        <th scope="col"><p align = "center"><abbr title="Carga Horária">C.H.</abbr></p></th>
        <th scope="col"><p align = "center">Avaliações</p></th>
      </tr>
    </thead>

    <tbody>
      {% for p in planos_trab_pessoa %}
      <tr>
        <th scope="row"><p align = "center"> 
          {{planos_trab_pessoa.index(p) + 1}} </p>
        </th>
        <td><p align = "center"> {{p.sigla}} </p></td>
        <td><p align = "center"> {{p.data_inicio.strftime('%d/%m/%Y')}} </p></td>
        <td><p align = "center"> {{p.data_fim.strftime('%d/%m/%Y')}} </p></td> 
        <td><p align = "center"> {{p.forma}} </p></td>
        <td><p align = "center"> 
            {% if p.status == 'ATIVO' %}
              <span class="text-primary">{{p.status}}</span>
            {% elif p.status == 'AGUARDANDO_ASSINATURA' %}
              <span class="text-warning">{{p.status}}</span>
            {% elif p.status == 'CONCLUIDO' and p.qtd_aval > 0 %}
              <span class="text-success">{{p.status}}</span>
            {% elif p.status == 'CONCLUIDO' and p.nota == 0 %}
              <span class="text-danger">{{p.status}}</span> 
            {% elif p.descricao == 'CANCELADO' %}
              <span class="text-info">{{p.status}}</span>        
            {% else %} 
              {{p.status}}  
            {% endif %} 
          </p> 
        </p></td>
        <td><p align = "center"> {{p.carga_horaria|decimal_com_virgula}} ({{p.forma_contagem_carga_horaria}}) </p></td>  

        <td><p align = "center">
          {% if p.qtd_aval != None %}
            <a style="text-decoration: none" href="{{url_for('trabalhos.consulta_avaliacoes',ptId=p.pt_id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
              {{ p.qtd_aval }}   </a>
          {% else %}
            NÃO HÁ
          {% endif%}
        </p></td>
        
        
      </tr>
      {% endfor %}
    </tbody>

  </table>

</div>

</div>
{% endblock %}

project/pessoas/templates/lista_pessoas_filtro.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('pessoas.lista_pessoas')}}">Pessoas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Pessoas (Filtro)</span></li>
    </ul>
  </div>
</div>

<!-- <div class="jumbotron"> -->
  <div class="card">
    <div class="card-header">
      <div class="d-flex flex-column flex-md-row justify-content-between">
        <h4 class="header-list">Lista das Pessoas 
            <br><small>Filtro aplicado: Nome <b>"{{p_nome}}"</b>, Unidade <b>"{{p_unid}}"</b>, Atrib. <b>"{{p_atrib}}"</b>, Sit. <b>"{{p_situ}}"</b>, Perf. <b>"{{p_perf}}"</b>
        </h4>

        <a href="{{url_for('pessoas.csv_pessoas_filtro', filtro=filtro)}}" class="br-button secondary mr-3" role="button">
                          <i class="fa-solid fa-file"></i>&nbsp; Gerar CSV</a>

      </div>
      
    </div>
    <div class="card-body">

      <span class="badge text-bg-warning">{{quantidade}}</span> registros na lista, conforme filtro aplicado  
        
      </p>
      <table style="width: 100%" id="table"
        data-toggle="table"
        data-filter-control="true"
        data-show-search-clear-button="true"
        data-sortable="true"
        classes="table-sm"
        data-show-columns="true"
        data-show-columns-toggle-all="true"
        class="table table-striped table-hover table-sm">
        <colgroup>
          <col span="1" style="width: 2%;">
          <col span="1" style="width: 18%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
       </colgroup>

        <caption>Pessoas</caption>
        <thead>
          <tr>
            <th scope="col"><p align = "center">#</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Nome</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Data Nasc.</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Mat.</p></th>
            <th scope="col" data-sortable="true"><p align = "center">E-mail</p></th>
            <th scope="col" data-field="undSigla" data-filter-control="input" data-sortable="true"><p align = "center">Unidade</p></th>
            <th scope="col" data-field="tfnDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Atribuição</p></th>
            <th scope="col" data-field="spsDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Situação</p></th>
            <th scope="col" data-field="tvnDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Perfil</p></th>
            <th scope="col" data-sortable="true"><p align = "center">PTs</p></th>
          </tr>
        </thead>
        <tbody>
          {% for p in pessoas %}

          <tr>
            <th scope="row"> <p align = "center">{{ pessoas.index(p) + 1 }} </p></th>
            <td><p align = "center"> {{p.nome}} </p></td>
            <td><p align = "center"> {% if p.data_nascimento == None or p.data_nascimento == '' %}N.I.{% else %}{{p.data_nascimento.strftime('%d/%m/%Y')}}{%endif%} </p></td>
            <td><p align = "center"> {{p.matricula}} </p></td>
            <td><p align = "center"> {% if p.email == None %}N.I.{% else %}{{p.email}}{% endif %} </p></td>
            <td><p align = "center"> {% if p.sigla == None %}N.I.{% else %}{{p.sigla}}{% endif %} </p></td>
            <td><p align = "center"> {% if p.atribuicao == None %}N.I.{% else %}{{p.atribuicao}}{% endif %} </p></td>
            <td><p align = "center"> {{p.situacao_funcional}} </p></td>
            <td><p align = "center"> 
              {% if p.perfil == None %}
                N.I.
              {% else %}
                {% if p.perfil[:6] == 'Perfil' %}
                  {{ p.perfil[7:] }}
                {% else %}  
                  {{p.perfil}}
                {% endif %}  
              {% endif %} 
            </p></td>
            <td>  
              <p align = "center"> 
                {% if p.qtd_planos_trab == None or p.qtd_planos_trab == 0 %}
                  Não há
                {% else %}
                  <a style="text-decoration: none" href="{{url_for('pessoas.consulta_pts_pessoa',pessoa_id=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
                    {{p.qtd_planos_trab}}</a>
                {% endif %}
  
              </p>
            </td>  

          </tr>

          {% endfor %}

        </tbody>
      </table>

    </div>
  </div>
  
  



<!-- </div> -->
{% endblock %}

project/pessoas/templates/lista_pessoas_gestor.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      {% if tipo == "pesq" %}
        <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('pessoas.lista_pessoas')}}">Pessoas</a></li>
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Pessoas (Filtro)</span></li>
      {% else %}    
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Pessoas</span></li>
      {% endif %}
    </ul>
  </div>
</div>

<!-- <div class="jumbotron"> -->
  <div class="card">
    <div class="card-header">
      <div class="d-flex flex-column flex-md-row justify-content-between">
        <h4 class="header-list">Lista das Pessoas 
          {% if tipo == "inst" %}na Instituição
          {% elif tipo == "pesq" %} 
            <br><small>Filtro aplicado: Nome <b>"{{p_nome}}"</b>, Unidade <b>"{{p_unid}}"</b>, Atrib. <b>"{{p_atrib}}"</b>, Sit. <b>"{{p_situ}}"</b>, Perf. <b>"{{p_perf}}"</b>
          {% else %}na Unidade
          {% endif %}</h4>

        <div class="d-flex justify-content-around">

            <a href="{{url_for('pessoas.lista_pessoas_filtro')}}" class="br-button secondary mr-3" role="button"><i class="fa fa-filter" aria-hidden="true"></i>Filtro</a>

        </div>
      </div>
      
    </div>
    <div class="card-body">
       
        {% if tipo == "inst" %}
          <p><span class="badge text-bg-primary">{{qtd_pessoas}}</span> pessoas na Instituição (<span class="badge text-bg-warning">{{quantidade}}</span> registros na lista)
        {% elif tipo == "pesq" %}
          <span class="badge text-bg-warning">{{quantidade}}</span> registros na lista, conforme filtro aplicado  
        {% endif %}
        
      </p>
      <table style="width: 100%" id="table"
        data-toggle="table"
        data-filter-control="true"
        data-show-search-clear-button="true"
        data-sortable="true"
        classes="table-sm"
        data-show-columns="true"
        data-show-columns-toggle-all="true"
        class="table table-striped table-hover table-sm">
        <colgroup>
          <col span="1" style="width: 2%;">
          <col span="1" style="width: 18%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
          <col span="1" style="width: 10%;">
       </colgroup>

        <caption>Pessoas</caption>
        <thead>
          <tr>
            <th scope="col"><p align = "center">#</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Nome</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Data Nasc.</p></th>
            <th scope="col" data-sortable="true"><p align = "center">Mat.</p></th>
            <th scope="col" data-sortable="true"><p align = "center">E-mail</p></th>
            <th scope="col" data-field="undSigla" data-filter-control="input" data-sortable="true"><p align = "center">Unidade</p></th>
            <th scope="col" data-field="tfnDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Atribuição</p></th>
            <th scope="col" data-field="spsDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Situação</p></th>
            <th scope="col" data-field="tvnDescricao" data-filter-control="input" data-sortable="true"><p align = "center">Perfil</p></th>
            <th scope="col" data-sortable="true"><p align = "center">PTs</p></th>
          </tr>
        </thead>
        <tbody>
          {% for p in pessoas.items %}

          <tr>
            <th scope="row"> <p align = "center">{{(pessoas.page - 1) * pessoas.per_page + pessoas.items.index(p) + 1}} </a> </p></th>
            <td><p align = "center"> {{p.nome}} </p></td>
            <td><p align = "center"> {% if p.data_nascimento == None or p.data_nascimento == '' %}N.I.{% else %}{{p.data_nascimento.strftime('%d/%m/%Y')}}{%endif%} </p></td>
            <td><p align = "center"> {{p.matricula}} </p></td>
            <td><p align = "center"> {% if p.email == None %}N.I.{% else %}{{p.email}}{% endif %} </p></td>
            <td><p align = "center"> {% if p.sigla == None %}N.I.{% else %}{{p.sigla}}{% endif %} </p></td>
            <td><p align = "center"> {% if p.atribuicao == None %}N.I.{% else %}{{p.atribuicao}}{% endif %} </p></td>
            <td><p align = "center"> {{p.situacao_funcional}} </p></td>
            <td><p align = "center"> 
              {% if p.perfil == None %}
                N.I.
              {% else %}
                {% if p.perfil[:6] == 'Perfil' %}
                  {{ p.perfil[7:] }}
                {% else %}  
                  {{p.perfil}}
                {% endif %}  
              {% endif %} 
            </p></td>
            <td>  
              <p align = "center"> 
                {% if p.qtd_planos_trab == None or p.qtd_planos_trab == 0 %}
                  Não há
                {% else %}
                  <a style="text-decoration: none" href="{{url_for('pessoas.consulta_pts_pessoa',pessoa_id=p.id)}}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
                    {{p.qtd_planos_trab}}</a>
                {% endif %}
  
              </p>
            </td>  

          </tr>

          {% endfor %}

        </tbody>
      </table>
      <nav class="br-pagination"  aria-label="Page navigation">
        <ul class="pagination justify-content-center">
      
          {% for page_num in pessoas.iter_pages(left_edge=1,left_current=1,right_current=2,right_edge=1) %}
            {% if page_num %}
              {% if pessoas.page == page_num %}
                <li>
                    <a class="page active" href="{{url_for('pessoas.lista_pessoas',page=page_num)}}">{{page_num}}</a>
                </li>
              {% else %}
                <li>
                    <a class="page" href="{{url_for('pessoas.lista_pessoas',page=page_num)}}">{{page_num}}</a>
                </li>
              {% endif %}
            {% else %}
              <span class="page">…</span>
            {% endif %}
      
          {% endfor %}
        </ul>
      </nav>
    </div>
  </div>
  
  



<!-- </div> -->
{% endblock %}

project/pessoas/templates/pesquisa_pessoas.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('pessoas.lista_pessoas')}}">Pessoas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Pesquisa em Pessoas</span>
      </li>
    </ul>
  </div>
</div>


<div class="container">

<div class="jumbotron">
<h1>Filtro para lista de Pessoas</h1>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form class="needs-validation" method='POST' >
  {{ form.hidden_tag() }}

  <div class = "row">
    <div class="col-10">
      <div class="form-group">
        {{ render_field(form.nome,class="form-control",obr=False) }}
      </div>
    </div>
  </div>

  <div class = "row">

    <div class="col-2">
      <div class="form-group">
        {{ render_field(form.unidade,class="form-control", obr=False) }}
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        {{ render_field(form.situ,class="form-control", obr=False) }}
      </div>
    </div>
    <div class="col-4">
      <div class="form-group">
        {{ render_field(form.atrib,class="form-control", obr=False) }}
      </div>
    </div>
    <div class="col-3">
      <div class="form-group">
        {{ render_field(form.perf,class="form-control", obr=False) }}
      </div>
    </div>

  </div>
  
  <div class="row mt-4">
    <div class="col-8"></div>
    <div class="form-group">
      {{ form.submit(class="br-button secondary mr-3") }}
    </div>
  </div>

</div>
</div>

{% endblock %}